import {NextAuthProvider} from '@/providers/NextAuthProvider';
import {PageProvider} from '@/providers/PageProvider';
import '@/styles/globals.css';
import BottomNavBar from '@/ui/layout/BottomNavBar';
import Header from '@/ui/layout/header';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <PageProvider>
            <Header />
            <div className="h-screen px-4 md:px-8 pb-bottom-nav-height overflow-auto pt-header-height md:pt-desktop-header-height">
              {children}
            </div>
            <BottomNavBar />
          </PageProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
