import {NextAuthProvider} from '@/providers/NextAuthProvider';
import {PageProvider} from '@/providers/PageProvider';
import '@/styles/globals.css';
import BottomNavBar from '@/ui/layout/BottomNavBar';
import Header from '@/ui/layout/header';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {NavBarHeight} from '../../const';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <PageProvider>
            <Header />
            {/* padding-top은 header 높이 */}
            <div
              style={{
                paddingBottom: NavBarHeight + 'px',
                minHeight: 'calc(100% - NavBarHeight)',
              }}
              className="px-8 pt-[48px] md:pt-[56px]"
            >
              {children}
            </div>
            <BottomNavBar />
          </PageProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
